app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/**
 * Model binding into route
 */
Route::model('blogcategory', 'App\BlogCategory');
Route::model('blog', 'App\Blog');
Route::model('file', 'App\File');
Route::model('task', 'App\Task');
Route::model('users', 'App\User');

Route::pattern('slug', '[a-z0-9- _]+');

Route::group(array('prefix' => 'admin'), function () {

	# Error pages should be shown without requiring login
	Route::get('404', function () {
		return View('admin/404');
	});
	Route::get('500', function () {
		return View::make('admin/500');
	});





    Route::post('/move-reservation', array('as' => 'move-reservation','uses' => 'ReservationController@moveReservation'));
    Route::post('/resize-reservation', array('as' => 'resize-reservation','uses' => 'ReservationController@resizeReservation'));
    Route::post('/delete-reservation', array('as' => 'delete-reservation','uses' => 'ReservationController@deleteReservation'));
    Route::get('/edit-reservation/{id}', array('as' => 'edit-reservation','uses' => 'ReservationController@editReservation'));
    Route::get('/new-reservation', array('as' => 'new-reservation','uses' => 'ReservationController@newReservation'));
    Route::post('/get-reservation', array('as' => 'get-reservation','uses' => 'ReservationController@getReservation'));
    Route::post('update-reservation', array('as' => 'update-reservation','uses' => 'ReservationController@updateReservation'));
    Route::post('get-rooms', array('as' => 'get-rooms','uses' => 'RoomController@getRooms'));
    Route::get('get-rooms', array('as' => 'get-rooms','uses' => 'RoomController@getRooms'));
    Route::get('/reservation', array('as' => 'reservation','uses' => 'ReservationController@getRoomPlan'));
    Route::get('/reservation/{start}/{end}/{moveval}', array('as' => 'reservation','uses' => 'ReservationController@getRoomPlan'));
    Route::post('/change-reservation', array('as' => 'change-reservation','uses' => 'ReservationController@getChangeRoomPlan'));






    Route::post('secureImage', array('as' => 'secureImage','uses' => 'JoshController@secureImage'));

	# Lock screen
	Route::get('{id}/lockscreen', array('as' => 'lockscreen', 'uses' =>'UsersController@lockscreen'));

	# All basic routes defined here
	Route::get('signin', array('as' => 'signin', 'uses' => 'AuthController@getSignin'));
	Route::post('signin', 'AuthController@postSignin');
	Route::post('signup', array('as' => 'signup', 'uses' => 'AuthController@postSignup'));
	Route::post('forgot-password', array('as' => 'forgot-password', 'uses' => 'AuthController@postForgotPassword'));
	Route::get('login2', function () {
		return View::make('admin/login2');
	});

	# Register2
	Route::get('register2', function () {
		return View::make('admin/register2');
	});
	Route::post('register2', array('as' => 'register2', 'uses' => 'AuthController@postRegister2'));

	# Forgot Password Confirmation
	Route::get('forgot-password/{userId}/{passwordResetCode}', array('as' => 'forgot-password-confirm', 'uses' => 'AuthController@getForgotPasswordConfirm'));
	Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@postForgotPasswordConfirm');

	# Logout
	Route::get('logout', array('as' => 'logout', 'uses' => 'AuthController@getLogout'));

	# Account Activation
	Route::get('activate/{userId}/{activationCode}', array('as' => 'activate', 'uses' => 'AuthController@getActivate'));
});

Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {
    # Dashboard / Index
	Route::get('/', array('as' => 'dashboard','uses' => 'JoshController@showHome'));


    # User Management
    Route::group(array('prefix' => 'users'), function () {
        Route::get('/', array('as' => 'users', 'uses' => 'UsersController@index'));
        Route::get('data',['as' => 'users.data', 'uses' =>'UsersController@data']);
        Route::get('create', 'UsersController@create');
        Route::post('create', 'UsersController@store');
        Route::get('{userId}/delete', array('as' => 'delete/user', 'uses' => 'UsersController@destroy'));
        Route::get('{userId}/confirm-delete', array('as' => 'confirm-delete/user', 'uses' => 'UsersController@getModalDelete'));
        Route::get('{userId}/restore', array('as' => 'restore/user', 'uses' => 'UsersController@getRestore'));
        Route::get('{userId}', array('as' => 'users.show', 'uses' => 'UsersController@show'));
        Route::post('{userId}/passwordreset', array('as' => 'passwordreset', 'uses' => 'UsersController@passwordreset'));
    });
    Route::resource('users', 'UsersController');

	Route::get('deleted_users',array('as' => 'deleted_users','before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'));

	# Group Management
    Route::group(array('prefix' => 'groups'), function () {
        Route::get('/', array('as' => 'groups', 'uses' => 'GroupsController@index'));
        Route::get('create', array('as' => 'create/group', 'uses' => 'GroupsController@create'));
        Route::post('create', 'GroupsController@store');
        Route::get('{groupId}/edit', array('as' => 'update/group', 'uses' => 'GroupsController@edit'));
        Route::post('{groupId}/edit', 'GroupsController@update');
        Route::get('{groupId}/delete', array('as' => 'delete/group', 'uses' => 'GroupsController@destroy'));
        Route::get('{groupId}/confirm-delete', array('as' => 'confirm-delete/group', 'uses' => 'GroupsController@getModalDelete'));
        Route::get('{groupId}/restore', array('as' => 'restore/group', 'uses' => 'GroupsController@getRestore'));
    });
    /*routes for blog*/
	Route::group(array('prefix' => 'blog'), function () {
        Route::get('/', array('as' => 'blogs', 'uses' => 'BlogController@index'));
        Route::get('create', array('as' => 'create/blog', 'uses' => 'BlogController@create'));
        Route::post('create', 'BlogController@store');
        Route::get('{blog}/edit', array('as' => 'update/blog', 'uses' => 'BlogController@edit'));
        Route::post('{blog}/edit', 'BlogController@update');
        Route::get('{blog}/delete', array('as' => 'delete/blog', 'uses' => 'BlogController@destroy'));
		Route::get('{blog}/confirm-delete', array('as' => 'confirm-delete/blog', 'uses' => 'BlogController@getModalDelete'));
		Route::get('{blog}/restore', array('as' => 'restore/blog', 'uses' => 'BlogController@getRestore'));
        Route::get('{blog}/show', array('as' => 'blog/show', 'uses' => 'BlogController@show'));
        Route::post('{blog}/storecomment', array('as' => 'restore/blog', 'uses' => 'BlogController@storecomment'));
	});

    /*routes for blog category*/
	Route::group(array('prefix' => 'blogcategory'), function () {
        Route::get('/', array('as' => 'blogcategories', 'uses' => 'BlogCategoryController@index'));
        Route::get('create', array('as' => 'create/blogcategory', 'uses' => 'BlogCategoryController@create'));
        Route::post('create', 'BlogCategoryController@store');
        Route::get('{blogcategory}/edit', array('as' => 'update/blogcategory', 'uses' => 'BlogCategoryController@edit'));
        Route::post('{blogcategory}/edit', 'BlogCategoryController@update');
        Route::get('{blogcategory}/delete', array('as' => 'delete/blogcategory', 'uses' => 'BlogCategoryController@destroy'));
		Route::get('{blogcategory}/confirm-delete', array('as' => 'confirm-delete/blogcategory', 'uses' => 'BlogCategoryController@getModalDelete'));
		Route::get('{blogcategory}/restore', array('as' => 'restore/blogcategory', 'uses' => 'BlogCategoryController@getRestore'));
	});

	/*routes for file*/
	Route::group(array('prefix' => 'file'), function () {
        Route::post('create', 'FileController@store');
		Route::post('createmulti', 'FileController@postFilesCreate');
		Route::delete('delete', 'FileController@delete');
	});

	Route::get('crop_demo', function () {
        return redirect('admin/imagecropping');
    });
    Route::post('crop_demo','JoshController@crop_demo');

	/* laravel example routes */
	# datatables
	Route::get('datatables', 'DataTablesController@index');
	Route::get('datatables/data', array('as' => 'admin.datatables.data', 'uses' => 'DataTablesController@data'));

    # editable datatables
    Route::get('editable_datatables', 'DataTablesController@editableDatatableIndex');
    Route::get('editable_datatables/data', array('as' => 'admin.editable_datatables.data', 'uses' => 'DataTablesController@editableDatatableData'));
    Route::post('editable_datatables/create','DataTablesController@editableDatatableStore');
    Route::post('editable_datatables/{id}/update', 'DataTablesController@editableDatatableUpdate');
    Route::get('editable_datatables/{id}/delete', array('as' => 'admin.editable_datatables.delete', 'uses' => 'DataTablesController@editableDatatableDestroy'));

    //tasks section
    Route::post('task/create', 'TaskController@store');
    Route::get('task/data', 'TaskController@data');
    Route::post('task/{task}/edit', 'TaskController@update');
    Route::post('task/{task}/delete', 'TaskController@delete');


	# Remaining pages will be called from below controller method
	# in real world scenario, you may be required to define all routes manually

	Route::get('{name?}', 'JoshController@showView');

});

#FrontEndController
Route::get('login', array('as' => 'login','uses' => 'FrontEndController@getLogin'));
Route::post('login','FrontEndController@postLogin');
Route::get('register', array('as' => 'register','uses' => 'FrontEndController@getRegister'));
Route::post('register','FrontEndController@postRegister');

resources/views/admin/layouts/_messages.blade.php
<li class="dropdown messages-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="livicon"
                                                                   data-name="message-flag"
                                                                   data-loop="true" data-color="#42aaca"
                                                                   data-hovercolor="#42aaca"
                                                                   data-size="28"></i>
        <span class="label label-success">4</span>
    </a>
    <ul class="dropdown-menu dropdown-messages pull-right">
        <li class="dropdown-title">4 New Messages</li>
        <li class="unread message">
            <a href="javascript:;" class="message"> <i class="pull-right" data-toggle="tooltip"
                                                       data-placement="top" title="Mark as Read"><span
                            class="pull-right ol livicon" data-n="adjust" data-s="10"
                            data-c="#287b0b"></span></i>
                <img src="{{ asset('assets/img/authors/avatar.jpg') }}"
                     class="img-responsive message-image" alt="icon">

                <div class="message-body">
                    <strong>Riot Zeast</strong>
                    <br>Hello, You there?
                    <br>
                    <small>8 minutes ago</small>
                </div>
            </a>
        </li>
        <li class="unread message">
            <a href="javascript:;" class="message">
                <i class="pull-right" data-toggle="tooltip" data-placement="top"
                   title="Mark as Read"><span class="pull-right ol livicon" data-n="adjust" data-s="10"
                                              data-c="#287b0b"></span></i>
                <img src="{{ asset('assets/img/authors/avatar1.jpg') }}"
                     class="img-responsive message-image" alt="icon">

                <div class="message-body">
                    <strong>John Kerry</strong>
                    <br>Can we Meet ?
                    <br>
                    <small>45 minutes ago</small>
                </div>
            </a>
        </li>
        <li class="unread message">
            <a href="javascript:;" class="message">
                <i class="pull-right" data-toggle="tooltip" data-placement="top" title="Mark as Read">
                                    <span class="pull-right ol livicon" data-n="adjust" data-s="10"
                                          data-c="#287b0b"></span>
                </i>
                <img src="{{ asset('assets/img/authors/avatar5.jpg') }}"
                     class="img-responsive message-image" alt="icon">

                <div class="message-body">
                    <strong>Jenny Kerry</strong>
                    <br>Dont forgot to call...
                    <br>
                    <small>An hour ago</small>
                </div>
            </a>
        </li>
        <li class="unread message">
            <a href="javascript:;" class="message">
                <i class="pull-right" data-toggle="tooltip" data-placement="top" title="Mark as Read">
                                    <span class="pull-right ol livicon" data-n="adjust" data-s="10"
                                          data-c="#287b0b"></span>
                </i>
                <img src="{{ asset('assets/img/authors/avatar4.jpg') }}"
                     class="img-responsive message-image" alt="icon">

                <div class="message-body">
                    <strong>Ronny</strong>
                    <br>Hey! sup Dude?
                    <br>
                    <small>3 Hours ago</small>
                </div>
            </a>
        </li>
        <li class="footer">
            <a href="#">View all</a>
        </li>
    </ul>
</li>

resources/views/admin/layouts/_notifications.blade.php
<li class="dropdown notifications-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="livicon" data-name="bell" data-loop="true" data-color="#e9573f"
           data-hovercolor="#e9573f" data-size="28"></i>
        <span class="label label-warning">7</span>
    </a>
    <ul class=" notifications dropdown-menu">
        <li class="dropdown-title">You have 7 notifications</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li>
                    <i class="livicon danger" data-n="timer" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">after a long time</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        Just Now
                    </small>
                </li>
                <li>
                    <i class="livicon success" data-n="gift" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">Jef's Birthday today</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        Few seconds ago
                    </small>
                </li>
                <li>
                    <i class="livicon warning" data-n="dashboard" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">out of space</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        8 minutes ago
                    </small>
                </li>
                <li>
                    <i class="livicon bg-aqua" data-n="hand-right" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">New friend request</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        An hour ago
                    </small>
                </li>
                <li>
                    <i class="livicon danger" data-n="shopping-cart-in" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">On sale 2 products</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        3 Hours ago
                    </small>
                </li>
                <li>
                    <i class="livicon success" data-n="image" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">Lee Shared your photo</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        Yesterday
                    </small>
                </li>
                <li>
                    <i class="livicon warning" data-n="thumbs-up" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">David liked your photo</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        2 July 2014
                    </small>
                </li>
            </ul>
        </li>
        <li class="footer">
            <a href="#">View all</a>
        </li>
    </ul>
</li>

resources/views/admin/layouts/default.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>
        @section('title')
            | Property Management System
        @show
    </title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>


    <![endif]-->
    <!-- global css -->
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Property Management System" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <meta name="robots" content="index, follow">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <script src="/js/html5shiv.js" type="text/javascript"></script>
    <script src="/js/respond.min.js" type="text/javascript"></script>
    <script src="/assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="/assets/js/jquery-ui.min.js" type="text/javascript"></script>
    <script src="/js/daypilot/daypilot-all.min.js" type="text/javascript"></script>
    <link href="/assets/css/app.css" rel="stylesheet" type="text/css"/>
    <!-- font Awesome -->
    <script>
        /* $.ajaxSetup({
         headers: {
         'X-CSRF-TOKEN': "{{ csrf_token() }}"
         }
         }); */

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>

    <!-- end of global css -->
    <!--page level css-->
    @yield('header_styles')
            <!--end of page level css-->

<body class="skin-josh">
<header class="header">
    <a href="{{ route('dashboard') }}" class="logo" style="background-color: #444954; !important; vertical-align: middle;text-align: left;padding-left: 20px;">
        <span style="color: #fff;font-size: 25px">PMS</span>
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <div>
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <div class="responsive_nav"></div>
            </a>
        </div>


        <div class="navbar-right">
            <ul class="nav navbar-nav">
                @include('admin.layouts._messages')
                @include('admin.layouts._notifications')
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        @if(!empty(Sentinel::getUser()) && Sentinel::getUser()->pic)
                            <img src="{!! url('/').'/uploads/users/'.Sentinel::getUser()->pic !!}" alt="img" height="35px" width="35px"
                                 class="img-circle img-responsive pull-left"/>
                        @else
                            <img src="{!! asset('assets/img/authors/avatar3.jpg') !!} " width="35"
                                 class="img-circle img-responsive pull-left" height="35" alt="riot">
                        @endif
                        <div class="riot">
                            <div>
                                <?php if(!empty(Sentinel::getUser())){?>
                                <?php echo Sentinel::getUser()->first_name.' '.Sentinel::getUser()->last_name ;?>
                                <?php } else{ echo '';}?>
                                <span>
                                        <i class="caret"></i>
                                    </span>
                            </div>
                        </div>
                    </a>



                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header bg-light-blue">
                            @if(!empty(Sentinel::getUser()) && Sentinel::getUser()->pic)
                                <img src="{!! url('/').'/uploads/users/'.Sentinel::getUser()->pic !!}" alt="img"
                                     class="img-circle img-bor"/>
                            @else
                                <img src="{!! asset('assets/img/authors/avatar3.jpg') !!}"
                                     class="img-responsive img-circle" alt="User Image">
                            @endif
                            <p class="topprofiletext">
                                <?php if(!empty(Sentinel::getUser())){?>
                                <?php echo Sentinel::getUser()->first_name.' '.Sentinel::getUser()->last_name ;?>
                                <?php } else{ echo '';}?>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li>
                            <?php
                            if(!empty(Sentinel::getUser())){
                            ?>
                            <a href="{{ URL::route('users.show',Sentinel::getUser()->id) }}">
                                <?php
                                }
                                ?>

                                <i class="livicon" data-name="user" data-s="18"></i>
                                My Profile

                                <?php
                                if(!empty(Sentinel::getUser())){
                                ?>
                            </a>
                            <?php
                            }
                            ?>
                        </li>
                        <li role="presentation"></li>
                        <li>
                            <?php
                            if(!empty(Sentinel::getUser())){
                            ?>
                            <a href="{{ route('admin.users.edit', Sentinel::getUser()->id) }}">
                                <?php
                                }
                                ?>

                                <i class="livicon" data-name="gears" data-s="18"></i>
                                Account Settings
                                <?php
                                if(!empty(Sentinel::getUser())){
                                ?>
                            </a>
                            <?php
                            }
                            ?>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <?php
                                if(!empty(Sentinel::getUser())){
                                ?>
                                <a href="{{ URL::route('lockscreen',Sentinel::getUser()->id) }}">
                                    <?php
                                    }
                                    ?>

                                    <i class="fa fa-angle-double-right"></i>
                                    Lock
                                    <?php
                                    if(!empty(Sentinel::getUser())){
                                    ?>
                                </a>
                                <?php
                                }
                                ?>
                            </div>
                            <div class="pull-right">
                                <a href="{{ URL::to('admin/logout') }}">
                                    <i class="livicon" data-name="sign-out" data-s="18"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class="wrapper row-offcanvas row-offcanvas-left">
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="left-side sidebar-offcanvas">
        <section class="sidebar ">
            <div class="page-sidebar  sidebar-nav">
                <div class="nav_icons">
                    <ul class="sidebar_threeicons">
                        <!--<li>
                            <a href="{{ URL::to('admin/form_builder') }}">
                                <i class="livicon" data-name="hammer" title="Form Builder 1" data-loop="true"
                                   data-color="#42aaca" data-hc="#42aaca" data-s="25"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{{ URL::to('admin/form_builder2') }}">
                                <i class="livicon" data-name="list-ul" title="Form Builder 2" data-loop="true"
                                   data-color="#e9573f" data-hc="#e9573f" data-s="25"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{{ URL::to('admin/buttonbuilder') }}">
                                <i class="livicon" data-name="vector-square" title="Button Builder" data-loop="true"
                                   data-color="#f6bb42" data-hc="#f6bb42" data-s="25"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{{ URL::to('admin/gridmanager') }}">
                                <i class="livicon" data-name="new-window" title="Page Builder" data-loop="true"
                                   data-color="#37bc9b" data-hc="#37bc9b" data-s="25"></i>
                            </a>
                        </li>-->
                    </ul>
                </div>
                <div class="clearfix"></div>
                <!-- BEGIN SIDEBAR MENU -->
                @include('admin.layouts._left_menu')
                <!-- END SIDEBAR MENU -->
            </div>
        </section>
    </aside>
    <aside class="right-side">

        <!-- Notifications -->
        @include('notifications')

                <!-- Content -->
        @yield('content')

    </aside>
    <!-- right-side -->
</div>
<a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Return to top"
   data-toggle="tooltip" data-placement="left">
    <i class="livicon" data-name="plane-up" data-size="18" data-loop="true" data-c="#fff" data-hc="white"></i>
</a>
<!-- global js -->
<script src="{{ asset('assets/js/app.js') }}" type="text/javascript"></script>


<!-- end of global js -->
<!-- begin page level js -->
@yield('footer_scripts')
        <!-- end page level js -->
</body>
</html>

resources/views/admin/layouts/menu.blade.php
<li {!! (Request::is('admin/students') || Request::is('admin/students/create') || Request::is('admin/students/*') ? 'class="active"' : '') !!}>
    <a href="#">
        <i class="livicon" data-name="list-ul" data-size="18" data-c="#418BCA" data-hc="#418BCA" data-loop="true"></i>
        <span class="title">Students</span>
        <span class="fa arrow"></span>
    </a>
    <ul class="sub-menu">
        <li {!! (Request::is('admin/students') ? 'class="active" id="active"' : '') !!}>
            <a href="{{ URL::to('admin/students') }}">
                <i class="fa fa-angle-double-right"></i>
                Students
            </a>
        </li>
        <li {!! (Request::is('admin/students/create') ? 'class="active" id="active"' : '') !!}>
            <a href="{{ URL::to('admin/students/create') }}">
                <i class="fa fa-angle-double-right"></i>
                Add New Student
            </a>
        </li>
    </ul>
</li><li {!! (Request::is('admin/students') || Request::is('admin/students/create') || Request::is('admin/students/*') ? 'class="active"' : '') !!}>
    <a href="#">
        <i class="livicon" data-name="list-ul" data-size="18" data-c="#418BCA" data-hc="#418BCA" data-loop="true"></i>
        <span class="title">Students</span>
        <span class="fa arrow"></span>
    </a>
    <ul class="sub-menu">
        <li {!! (Request::is('admin/students') ? 'class="active" id="active"' : '') !!}>
            <a href="{{ URL::to('admin/students') }}">
                <i class="fa fa-angle-double-right"></i>
                Students
            </a>
        </li>
        <li {!! (Request::is('admin/students/create') ? 'class="active" id="active"' : '') !!}>
            <a href="{{ URL::to('admin/students/create') }}">
                <i class="fa fa-angle-double-right"></i>
                Add New Student
            </a>
        </li>
    </ul>
</li><li {!! (Request::is('admin/taruns') || Request::is('admin/taruns/create') || Request::is('admin/taruns/*') ? 'class="active"' : '') !!}>
    <a href="#">
        <i class="livicon" data-name="list-ul" data-size="18" data-c="#418BCA" data-hc="#418BCA" data-loop="true"></i>
        <span class="title">Taruns</span>
        <span class="fa arrow"></span>
    </a>
    <ul class="sub-menu">
        <li {!! (Request::is('admin/taruns') ? 'class="active" id="active"' : '') !!}>
            <a href="{{ URL::to('admin/taruns') }}">
                <i class="fa fa-angle-double-right"></i>
                Taruns
            </a>
        </li>
        <li {!! (Request::is('admin/taruns/create') ? 'class="active" id="active"' : '') !!}>
            <a href="{{ URL::to('admin/taruns/create') }}">
                <i class="fa fa-angle-double-right"></i>
                Add New Tarun
            </a>
        </li>
    </ul>
</li>